import React, { useState } from 'react';
import { useAppContext } from '../../store/AppContext';
import { useStore } from '../../store/useStore';
import { parsePCFText } from '../../engine/PcfParser';

export function InputTab() {
  const { dispatch } = useAppContext();
  const setZustandData = useStore(state => state.setDataTable);
  const setZustandProposals = useStore(state => state.setProposals);
  const [text, setText] = useState('');

  const handlePullFromFinalPcf = () => {
    // Attempt to pull raw PCF text from the target app's output tab textarea, or input
    let pcfText = '';
    const outputTextArea = document.getElementById('output-textarea');
    if (outputTextArea) {
        pcfText = outputTextArea.value;
    } else {
        // Fallback to checking the standard file input textarea from the target app
        const legacyPcfInput = document.getElementById('smart_fixer-pcf-input');
        if (legacyPcfInput) {
            pcfText = legacyPcfInput.value;
        }
    }

    if (pcfText) {
        setText(pcfText);
    } else {
        alert("No PCF text found in the source application's output or input text areas.");
    }
  };

  const handleProcessPcf = () => {
    if (!text.trim()) {
      alert("Please enter PCF text or pull from the final PCF.");
      return;
    }

    try {
        dispatch({ type: "RESET_ALL" });
        setZustandData([]);
        setZustandProposals([]);

        const { parsedData, logEntries } = parsePCFText(text);

        logEntries.forEach(entry => dispatch({ type: "ADD_LOG", payload: entry }));

        dispatch({ type: "SET_DATA_TABLE", payload: parsedData });
        dispatch({ type: "SET_STATUS_MESSAGE", payload: `Import successful: ${parsedData.length} components loaded.` });

        alert(`Successfully imported ${parsedData.length} components. Proceed to 3DTopo Data Table.`);
    } catch (err) {
        console.error(err);
        alert(`Error parsing PCF: ${err.message}`);
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-16rem)] p-4 bg-white rounded shadow-sm border border-slate-200">
      <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-bold text-slate-700">Input PCF</h2>
          <div className="space-x-2">
              <button
                  onClick={handlePullFromFinalPcf}
                  className="px-4 py-2 bg-slate-600 hover:bg-slate-700 text-white font-medium rounded shadow transition"
              >
                  Pull from final PCF
              </button>
              <button
                  onClick={handleProcessPcf}
                  className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded shadow transition"
              >
                  Process PCF to Data Table
              </button>
          </div>
      </div>

      <p className="text-sm text-slate-500 mb-2">
          Paste your raw PCF text below, or use the "Pull from final PCF" button to fetch data generated by the PCF Converter Application.
      </p>

      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        className="flex-1 w-full p-3 font-mono text-sm border border-slate-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none bg-slate-50"
        placeholder="Paste PCF content here..."
      />
    </div>
  );
}
